name: Build Android App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Add Android Platform
        run: npx cap add android

      - name: Generate Resources
        run: npx capacitor-assets generate

      - name: Copy Google Services File
        run: cp google-services.json android/app/

      - name: Make Gradlew Executable
        run: chmod +x android/gradlew
        
      - name: Build APK
        run: cd android && ./gradlew assembleDebug

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-build
          path: android/app/build/outputs/apk/debug/app-debug.apk
