name: Build Android APK with Icon and Splash

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Java (JDK 17)
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      # التعديل هنا في هذه الخطوة
      - name: Generate App Icons and Splash Screen
        run: |
          npm install -g @capacitor/assets
          # تم تبسيط الأمر ليتوافق مع الإصدارات الجديدة
          capacitor-assets generate --android

      - name: Clean and Re-add Android Platform
        run: |
          rm -rf android
          npx cap add android

      - name: Sync Web Assets
        run: npx cap sync android

      - name: Create local.properties
        run: echo 'sdk.dir=/usr/lib/android-sdk' > android/local.properties

      - name: Grant execute permission for gradlew
        run: chmod +x android/gradlew
        
      - name: Build Debug APK
        run: cd android && ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-with-icon-and-splash
          path: android/app/build/outputs/apk/debug/app-debug.apk
