name: Build Android APK with all features

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java (JDK 17)
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      # لن نقوم بحذف مجلد android بعد الآن
      # سنقوم فقط بتشغيل sync لتحديثه
      - name: Sync Web Assets and Plugins
        run: npx cap sync android

      - name: Grant execute permission for gradlew
        run: chmod +x android/gradlew
        
      - name: Build Debug APK
        run: cd android && ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: final-app
          path: android/app/build/outputs/apk/debug/app-debug.apk
