name: Build Stable Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java (JDK 17)
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          # تفعيل التخزين المؤقت لـ npm لتسريع العمليات
          cache: 'npm'

      - name: Install All Dependencies
        run: npm install

      # في الإصدار القديم، نحتاج لإنشاء مجلد android أولاً
      - name: Add Android Platform
        run: npx cap add android

      # ثم نولد الأصول
      - name: Generate App Icons and Splash Screen
        run: npx capacitor-assets generate --android

      # ثم ننسخ ملف إعدادات Firebase
      - name: Copy google-services.json
        run: cp google-services.json android/app/
      
      # أخيرًا، نقوم بمزامنة كل شيء
      - name: Sync Project
        run: npx cap sync android
        
      - name: Grant execute permission for gradlew
        run: chmod +x android/gradlew
        
      - name: Build Debug APK
        run: cd android && ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: stable-app-build
          path: android/app/build/outputs/apk/debug/app-debug.apk
