name: Fetch Football Matches Schedule

on:
  schedule:
    # يمكنك تحديد الوقت الذي تريده هنا (مثلاً كل 6 ساعات)
    - cron: '0 */6 * * *'
  workflow_dispatch: # هذا يسمح لك بتشغيله يدوياً من واجهة GitHub

jobs:
  fetch-and-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # استخدام إصدار حديث من نود

      # ▼▼▼ الخطوة الجديدة والمهمة ▼▼▼
      - name: Install dependencies
        run: npm install

      - name: Run fetch matches script
        # نقوم بتمرير المفاتيح السرية هنا
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        run: node scripts/fetch-matches.js
