# اسم الـ Workflow الذي يظهر في قائمة Actions
name: Fetch Football Matches Schedule

# متى يتم تشغيل هذا الـ Workflow
on:
  workflow_dispatch:

# المهام (Jobs) التي سيتم تنفيذها
jobs:
  fetch-and-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      # ▼▼▼ الخطوة الجديدة للتشخيص (مؤقتة) ▼▼▼
      - name: Debug Secrets
        run: |
          echo "Supabase URL is set: ${{ env.SUPABASE_URL != '' }}"
          echo "Supabase Key is set: ${{ env.SUPABASE_ANON_KEY != '' }}"
          echo "Football Data API Key is set: ${{ env.FOOTBALL_DATA_API_KEY != '' }}"
        # نقوم بتمرير المفاتيح السرية هنا أيضاً لنتمكن من فحصها
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          FOOTBALL_DATA_API_KEY: ${{ secrets.FOOTBALL_DATA_API_KEY }}

      # الخطوة الأصلية لتشغيل السكربت
      - name: Run fetch matches script
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          FOOTBALL_DATA_API_KEY: ${{ secrets.FOOTBALL_DATA_API_KEY }}
        run: node scripts/fetch-matches.js
